from setuptools import setup, find_packages

setup(
    name="movie-recommender",
    version="1.0.0",
    description="AI-Based Smart Movie Recommendation System",
    author="Your Name",
    author_email="your.email@example.com",
    packages=find_packages(),
    install_requires=[
        "fastapi==0.104.1",
        "uvicorn[standard]==0.24.0",
        "streamlit==1.28.1",
        "pandas==2.1.3",
        "numpy==1.24.3",
        "scikit-learn==1.3.2",
        "sentence-transformers==2.2.2",
        "faiss-cpu==1.7.4",
        "pydantic==2.5.0",
        "python-multipart==0.0.6",
        "requests==2.31.0",
        "plotly==5.17.0",
        "seaborn==0.13.0",
        "matplotlib==3.8.2",
    ],
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
)